name: Test 1Password Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Use the Go version you're developing with

      - name: Run tests
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET_REF1: ${{ secrets.SECRET_REF1 }}
          SECRET_VAL1: ${{ secrets.SECRET_VAL1 }}
          SECRET_REF2: ${{ secrets.SECRET_REF2 }}
          SECRET_VAL2: ${{ secrets.SECRET_VAL2 }}
          SECRET_REF3: ${{ secrets.SECRET_REF3 }}
          SECRET_VAL3: ${{ secrets.SECRET_VAL3 }}
          SECRET_REF_FAIL: ${{ secrets.SECRET_REF_FAIL }}
        run: |
          go test -v ./...
